


FROM python:3.6
LABEL maintainer="ninad_kanthi@hotmail.com"

RUN mkdir /home/python
RUN mkdir /home/python/yolo
RUN mkdir /home/python/mobileNet

ENV PATH="/home/python:${PATH}"


RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
        && apt-get install -y wget \
        && pip install opencv-contrib-python \
        && pip install flask \
        && pip install flask_cors \
        && pip install azure-storage-file \
        && pip install azure-storage-blob \
        && pip install azure-storage-common \
        && pip install azure-cosmos \
        && pip install azure-keyvault \
        && pip install azure-eventhub \
        && pip install expiringdict \
        && pip install google-api-core \
        && pip install google-auth \
        && pip install google-cloud-automl \
        && pip install google-cloud-vision \
        && pip install googleapis-common-protos \    
        && pip install PyJWT \
        && pip install requests-oauthlib \
        && pip install rsa \               
        && pip install uamqp

WORKDIR /home/python

#EXPOSE 443 5000 2222

# copy python files
# dir /b *.py > pythonFile.txt
# replace ^ 'COPY ' 
# replace $ ' ./'

COPY asyncioBase.py ./
COPY azureImageDetector.py ./
COPY common.py ./
COPY cosmosBase.py ./
COPY cosmosDBApiMapper.py ./
COPY cosmosDBWrapper.py ./
COPY cosmosImageOperations.py ./
COPY cosmosStatusUpdate.py ./
COPY docker_clsOpenCVProcessImages.py ./
COPY eventMessageProcessor.py ./
COPY eventMessageSender.py ./
COPY eventProcessorHost.py ./
COPY eventReceiver.py ./
COPY googleImageDetector.py ./
COPY imageDetectorTest.py ./
COPY loggingBase.py ./
COPY mobileNetImageDetector.py ./
COPY openCVPhotoExtractor.py ./
COPY openCVPhotoExtractorClsImpl.py ./
COPY openCVPhotoExtractorTest.py ./
COPY storageFileService.py ./
COPY yoloBirdImageDetector.py ./

# copy additional files
COPY yolo/coco.names ./yolo/
COPY yolo/yolov3.cfg ./yolo/
#COPY yolo/yolov3.weights ./yolo/
RUN wget https://pjreddie.com/media/files/yolov3.weights -O ./yolo/yolov3.weights

COPY mobileNet/MobileNetSSD_deploy.caffemodel ./mobileNet/
COPY mobileNet/MobileNetSSD_deploy.prototxt.txt ./mobileNet/


# copy start-up files
COPY processExperimentReceiver.sh ./

# copy configuration files
COPY docker/keys/keys.sh ./
COPY docker/keys/key.json ./
COPY docker/initPythonCore.sh ./

RUN chmod +x processExperimentReceiver.sh
RUN chmod +x initPythonCore.sh

ENTRYPOINT ["./initPythonCore.sh"]