FROM python:3.6
LABEL maintainer="ninad_kanthi@hotmail.com"

RUN mkdir /home/azurefs

ENV PATH="/home/azurefs:${PATH}"

# ssh
ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
        && apt-get install -y --no-install-recommends openssh-server \
        && echo "$SSH_PASSWD" | chpasswd \
        && pip install opencv-contrib-python \
        && pip install flask \
        && pip install flask_cors \
        && pip install azure-storage-file \
        && pip install gunicorn

WORKDIR /home/azurefs

COPY docker/sshd_config /etc/ssh/

EXPOSE 443 5000 2222

# copy python files
COPY azureFS/azure-api.py ./
COPY azureFS/azureCommon.py ./
COPY azureFS/azureFileShareTest.py ./
COPY azureFS/mask_creation.py ./
COPY azureFS/__init__.py ./

# copy start-up files
COPY azureFS/install/init_azurefs.sh ./
COPY azureFS/install/startUnicorn.sh ./
#copy certificate file
COPY docker/keys/privkey.key ./
COPY docker/keys/fullchain.pem ./

RUN chmod +x init_azurefs.sh
RUN chmod +x startUnicorn.sh

ENTRYPOINT ["./init_azurefs.sh"]